config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  root to: 'categories#index'

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end
  get '/cart', to: 'order_items#index'
  resources :order_items, path: '/cart/items'

  get '/cart/checkout', to: 'orders#new', ad: :checkout
  patch '/cart/checkout', to: 'orders#create'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

	has_many :product_categories
	has_many :products, through: :product_categories

end

app/models/order.rb
class Order < ApplicationRecord
	has_many :items, class_name: 'OrderItem'
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order
	belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord

	

	has_many :product_categories
	has_many :order_items
	has_many :categories, through: :product_categories
	has_many :vars, class_name: 'ProductVar'

end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
  belongs_to :product
  belongs_to :category
end

app/models/product_var.rb
class ProductVar < ApplicationRecord
	belongs_to :product 
end

app/models/shopping_cart.rb
class ShoppingCart

  delegate :sub_total, to: :order 

  def initialize(token:)
    @token = token
  end

  def order
    @order ||= Order.find_or_create_by(token: @token) do |order|
      order.sub_total = 0
    end
  end

  def items_count
    order.items.sum(:quantity)
  end

  def add_item(product_id:, quantity: 1)
    product = Product.find(product_id)

    order_item = order.items.find_or_initialize_by(product_id: product_id)

    order_item.price = product.price
    order_item.quantity = quantity

    ActiveRecord::Base.transaction do # exception treatment
      order_item.save
      update_sub_total!
    end
  end

  def remove_item(id:)
    ActiveRecord::Base.transaction do #exception treatment
      order.items.destroy(id)
      update_sub_total!
    end
  end


  private  
  def update_sub_total!
    order.sub_total = order.items.sum('quantity * price')
    order.save
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  before_action :current_cart

  def current_cart
    @current_cart ||= ShoppingCart.new(token: cart_token)
  end
  helper_method :current_cart

  private

  def cart_token
    return @cart_token unless @cart_token.nil?

    session[:cart_token] ||= SecureRandom.hex(8)
    @cart_token = session[:cart_token]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

	def index
		 @categories = Category.joins(:products).select('categories.*, count(products.id) as products_count').group('categories.id').order(:title)
		
	end

end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_action :authenticate_user!
  def index
    @items = current_cart.order.items
  end

  def create
    current_cart.add_item(
      product_id: params[:product_id],
      quantity: params[:quantity]
    )

    redirect_to cart_path
  end

  def destroy
    current_cart.remove_item(id: params[:id])
    redirect_to cart_path
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	
	def new
		@order = current_cart.order
	end

	def create
		@order = current_cart.order

		if @order.update_attributes(order_params.merge(status: 'open'))
			session[:cart_token] = nil
			redirect_to root_path
		else
			render :new
		end
	end

	private

	def order_params
		params.require(:order).permit(:authenticate_user!)
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @category = Category.find(params[:category_id])
    @products = @category.products.includes(:vars).order(:title)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/index.html.erb
<h2>Categories (<%= @categories.length %>)</h2>

<ol>
  <% @categories.each do |category| %>
    <li>
      <%= link_to category_products_path(category) do %>
        <%= category.title %>
        (<%= category.products_count %> products)
      <% end %>
    </li>
  <% end %>
</ol>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ohboy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p>
      <%= link_to "Home", root_path %> |
      <%= link_to pluralize(current_cart.items_count, 'item'), cart_path %> 
    </p>

    <hr />

    <%= yield %>
  </body>
</html>

app/views/order_items/index.html.erb
<h2>Current Cart</h2>

<table>
  <thead>
    <tr>
      <td>Product</td>
      <td>Price</td>
      <td>Quantity</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.product.title %></td>
        <td><%= number_to_currency item.price %></td>
        <td><%= item.quantity %></td>
        <td>
          <%= form_for item, method: :delete do |f| %>
            <%= f.submit "Remove" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
  <tfoot>
    <tr>
      <td colspan="4" align="right">
        <%= number_to_currency current_cart.sub_total %>
      </td>
    </tr>
  </tfoot>

</table>

<%= link_to "Checkout", categories_path %>

app/views/orders/new.html.erb
<h2>Checkout</h2>

<%= form_for @order do |f| %>

	<div class="form-group">
		<%= f.label :first_name %>
		<%= f.text_field :first_name %>
	</div>

	<div class="form-group">
		<%= f.label :last_name %>
		<%= f.text_field :last_name %>
	</div>

	<%= f.submit 'Checkout' %>


<% end %>

app/views/products/index.html.erb
<h2>
  <%= link_to "Categories", root_path %> /
  <%= @category.title %> /
  Products
</h2>

<ol>
  <% @products.each do |product| %>
    <li>
      <%= product.title %> (<%= number_to_currency product.price %>)

      <%= form_tag order_items_path do %>
        <%= hidden_field_tag :product_id, product.id %>
        <%= number_field_tag :quantity, 1 %>
        <%= submit_tag "Add to Cart" %>
      <% end %>

      <ul>
        <% product.vars.each do |variant| %>
          <li><%= variant.title %> (<%= number_to_currency variant.price %>)</li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ol>